# Generated by Django 5.0.2 on 2024-03-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('contact', models.CharField(max_length=100)),
                ('live_location', models.CharField(max_length=100)),
                ('house_type', models.CharField(max_length=100)),
            ],
        ),
    ]
